import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Header } from "@/shared/components/header";
import { Providers } from "../providers";
import { NavList } from "@/shared/components/nav-list";
import { RightSide } from "@/shared/components/right-side";
import { Container } from "@/shared/components/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Header />
          <Container>
            <div className="grid grid-cols-[auto_1fr_auto] gap-4">
              <NavList />
              {modal}
              {children}
              <RightSide />
            </div>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
